# -*- coding: utf-8 -*-
"""coutour edge detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDoeHKksrhp73a3k1rHZtjDZ_5ItG5Pe
"""

from google.colab import files
files.upload()
import cv2
import sys
import matplotlib.pyplot as plt

# Image path
image_path = "/content/IMG-20250916-WA0009.jpg"

# Read image
image = cv2.imread(image_path)

if image is None:
    print("❌ Image not loaded")
    sys.exit(0)

# Resize
image = cv2.resize(image, (600, 400))

# Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Edge detection
edges = cv2.Canny(gray, 50, 150)

# Find contours
contours, _ = cv2.findContours(
    edges,
    cv2.RETR_EXTERNAL,
    cv2.CHAIN_APPROX_SIMPLE
)

# Draw contours
contour_image = image.copy()
cv2.drawContours(contour_image, contours, -1, (0, 255, 0), 2)

# Convert BGR to RGB for Matplotlib
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
contour_rgb = cv2.cvtColor(contour_image, cv2.COLOR_BGR2RGB)

# SIDE-BY-SIDE DISPLAY
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(edges, cmap='gray')
plt.title("Edge Detection")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(contour_rgb)
plt.title("Contour-Based Edges")
plt.axis("off")

plt.show()